# Generated by Django 4.0.5 on 2023-04-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('northwest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('number_of_seats', models.IntegerField()),
                ('depart_time', models.TimeField()),
                ('depart_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_flight', to='northwest.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flight', to='northwest.airport')),
            ],
        ),
    ]
